# Generated by Django 4.2.6 on 2023-10-20 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_alter_phone_id_alter_phone_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f0ce538-e65d-4bec-8975-71fe489c081a'), primary_key=True, serialize=False, unique=True),
        ),
    ]
