# Generated by Django 4.2.6 on 2023-10-20 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_alter_phone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.UUIDField(default=uuid.UUID('14a0f56c-188b-48d8-b200-c237e6326542'), primary_key=True, serialize=False, unique=True),
        ),
    ]
