# Generated by Django 4.2.1 on 2023-06-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='person',
            field=models.ManyToManyField(blank=True, to='person.person'),
        ),
    ]
