# Generated by Django 4.2 on 2023-05-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('house', '0002_house_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
